- name: Cassandra exporter config file template
  template:
    src: templates/cassandra_config.yml
    dest: /opt/cassandra_exporter/cassandra_config.yml
    owner: root
    group: root
    mode: 0644

